### ISSUE TITLE
Which version of zig should OKRedis use ?

### ISSUE THREAD

**Issue by wangrw21** [kristoff-it/zig-okredis#11]
version ?

**Comment by tentaclius** [comment]
I'd like to know as well. Doesn't build with Zig 0.11.0 due to extra captures in for loop in multiple places.

**Comment by joachimschmidt557** [comment]
As mentioned, OkRedis intends to support `async` and thus implicitly expects Zig version 0.10.1. I will add this to the README. That being said, if there is demand for a version with more up-to-date support, I can add a `0.11.0` or `0.12.x` branch which tracks other Zig versions respectively.
